export const GET_ERROR = "GET_ERROR"

export const GET_ALL_CATEGORY = "GET_ALL_CATEGORY"
export const CREATE_CATEGORY = "CREATE_CATEGORY"
export const DELETE_CATEGORY = "DELETE_CATEGORY"
export const UPDATE_CATEGORY = "UPDATE_CATEGORY"

export const GET_ALL_BRAND = "GET_ALL_BRAND"
export const CREATE_BRAND = "CREATE_BRAND"

export const CREATE_SUB_CATEGORY = "CREATE_SUB_CATEGORY"
export const GET_SUB_CATEGORY = "GET_SUB_CATEGORY"

export const CREATE_PRODUCTS = "CREATE_PRODUCTS"
// export const GET_ONE_BRAND = "GET_ONE_BRAND"

export const GET_All_PRODUCTS = "GET_All_PRODUCTS"

export const GET_PRODUCT_DETAILS = "GET_PRODUCT_DETAILS"
export const GET_ONE_CATEGORY = "GET_ONE_CATEGORY"
export const GET_ONE_BRAND = "GET_ONE_BRAND"

export const GET_PRODUCT_LIKE = "GET_PRODUCT_LIKE"
export const DELETE_PRODUCT = "DELETE_PRODUCT"
export const UPDATE_PRODUCT = "UPDATE_PRODUCT"

export const CREATE_NEW_USER = "CREATE_NEW_USER"
export const LOGIN_USER = "LOGIN_USER"
export const GET_CURRENT_USER = "GET_CURRENT_USER"
export const FORGET_PASSWORD = "FORGET_PASSWORD"
export const VERIFY_PASSWORD = "VERIFY_PASSWORD"
export const RESET_PASSWORD = "RESET_PASSWORD"

export const CREATE_REVIEW = "CREATE_REVIEW"
export const ALL_REVIEWS_PRODUCT = "ALL_REVIEWS_PRODUCT"
export const DELETE_REVIEW = "DELETE_REVIEW"
export const UPDATE_REVIEW = "UPDATE_REVIEW"

export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST"
export const REMOVE_FROM_WISHLIST = "REMOVE_FROM_WISHLIST"
export const USER_WISHLIST = "USER_WISHLIST"

export const ADD_COUPON = "ADD_COUPON"
export const GET_All_COUPONS = "GET_All_COUPONS"
export const DELETE_COUPON = "DELETE_COUPON"
export const GET_ONE_COUPON = "GET_ONE_COUPON"
export const EDIT_COUPON = "EDIT_COUPON"






