export const GET_ERROR = "GET_ERROR"

export const GET_ALL_CATEGORY = "GET_ALL_CATEGORY"
export const CREATE_CATEGORY = "CREATE_CATEGORY"
export const DELETE_CATEGORY = "DELETE_CATEGORY"
export const UPDATE_CATEGORY = "UPDATE_CATEGORY"

export const GET_ALL_BRAND = "GET_ALL_BRAND"
export const CREATE_BRAND = "CREATE_BRAND"

export const CREATE_SUB_CATEGORY = "CREATE_SUB_CATEGORY"
export const GET_SUB_CATEGORY = "GET_SUB_CATEGORY"

export const CREATE_PRODUCTS = "CREATE_PRODUCTS"
// export const GET_ONE_BRAND = "GET_ONE_BRAND"

export const GET_All_PRODUCTS = "GET_All_PRODUCTS"

export const GET_PRODUCT_DETAILS = "GET_PRODUCT_DETAILS"
export const GET_ONE_CATEGORY = "GET_ONE_CATEGORY"
export const GET_ONE_BRAND = "GET_ONE_BRAND"

export const GET_PRODUCT_LIKE = "GET_PRODUCT_LIKE"
export const DELETE_PRODUCT = "DELETE_PRODUCT"
export const UPDATE_PRODUCT = "UPDATE_PRODUCT"

export const CREATE_NEW_USER = "CREATE_NEW_USER"
export const LOGIN_USER = "LOGIN_USER"
export const GET_CURRENT_USER = "GET_CURRENT_USER"
export const FORGET_PASSWORD = "FORGET_PASSWORD"
export const VERIFY_PASSWORD = "VERIFY_PASSWORD"
export const RESET_PASSWORD = "RESET_PASSWORD"

export const CREATE_REVIEW = "CREATE_REVIEW"
export const ALL_REVIEWS_PRODUCT = "ALL_REVIEWS_PRODUCT"
export const DELETE_REVIEW = "DELETE_REVIEW"
export const UPDATE_REVIEW = "UPDATE_REVIEW"

export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST"
export const REMOVE_FROM_WISHLIST = "REMOVE_FROM_WISHLIST"
export const USER_WISHLIST = "USER_WISHLIST"

export const ADD_COUPON = "ADD_COUPON"
export const GET_All_COUPONS = "GET_All_COUPONS"
export const DELETE_COUPON = "DELETE_COUPON"
export const GET_ONE_COUPON = "GET_ONE_COUPON"
export const EDIT_COUPON = "EDIT_COUPON"



export const ADD_USER_ADDRESSES = "ADD_USER_ADDRESSES"
export const GET_ALL_USER_ADDRESSES = "GET_ALL_USER_ADDRESSES"
export const DELETE_USER_ADDRESSES = "DELETE_USER_ADDRESSES"
export const GET_ONE_USER_ADDRESSES = "GET_ONE_USER_ADDRESSES"
export const UPDATE_USER_ADDRESSES = "UPDATE_USER_ADDRESSES"

export const UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE"
export const UPDATE_USER_PASSWORD = "UPDATE_USER_PASSWORD"

export const ADD_TO_CART = "ADD_TO_CART"
export const GET_ALL_USER_CART = "GET_ALL_USER_CART"
export const GLEAR_ALL_USER_CART = "GLEAR_ALL_USER_CART"
export const DELETE_ONE_ITRM_FROM_CART = "DELETE_ONE_ITRM_FROM_CART"
export const UPDATE_ITRM_FROM_CART = "UPDATE_ITRM_FROM_CART"

export const APPLY_COUPON = "APPLY_COUPON"



export const GET_All_PRODUCTS_BY_CATEGORY = "GET_All_PRODUCTS_BY_CATEGORY"
export const GET_All_PRODUCTS_BY_BRAND = "GET_All_PRODUCTS_BY_BRAND"

export const CREATE_ORDER_CASH = "CREATE_ORDER_CASH"
export const GET_ALL_ORDERS = "GET_ALL_ORDERS"
export const GET_ONE_ORDER = "GET_ONE_ORDER"
export const UPDATE_ORDER_PAY = "UPDATE_ORDER_PAY"
export const UPDATE_ORDER_DELIVER = "UPDATE_ORDER_DELIVER"
export const CREATE_ORDER_CARD = "CREATE_ORDER_CARD"
























